version: '3'
services:
  db:
    image: 'postgres:latest'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db